# Generated by Django 5.1.4 on 2025-01-04 13:11

import django.db.models.deletion
from django.db import migrations, models


def create_default_location(apps, schema_editor):
    Location = apps.get_model('meetups', 'Location')
    Location.objects.create(name='Default Location', address='Default Address')


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_meetup_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='meetup',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetups.location'),
        ),
        migrations.RunPython(create_default_location),
    ]
